export type IdiomaClave = "es" | "en"

export const idiomasDisponibles: IdiomaClave[] = ["es", "en"]

// ==========================================
// 1. TRADUCCIONES DE LA INTERFAZ GENERAL (UI)
// ==========================================
export const traduccionesUI: Record<IdiomaClave, Record<string, string>> = {
  es: {
    panelAdministrativo: "Panel Administrativo",
    gestion: "Gestión:",
    irPanelAdministrativo: "Ir al panel administrativo",
    perfil: "Perfil",
    historialReservas: "Historial Reservas",
    historialPagos: "Historial Pagos",
    cerrarSesion: "Cerrar sesión",
    idioma: "Idioma:",
    espanol: "Español",
    ingles: "Inglés",
    moneda: "Moneda:",
    usd: "USD ($)",
    crc: "CRC (₡)",
    contacto: "Contacto",
    contactoEmail: "Email: crtours0405@gmail.com",
    contactoTel: "Tel: +506 8716-2857",
    encuentraLugaresActividades: "Encuentra lugares y actividades",
    precioMinimo: "Precio mínimo",
    precioMaximo: "Precio máximo",
    buscar: "Buscar",
    limpiar: "Limpiar",
    exploraElMundoConNosotros: "Explora el mundo con nosotros",
    descubreDestinos: "Descubre destinos increíbles, reserva tus viajes y vive experiencias inolvidables.",
    verDestinos: "Ver destinos",
    toursDestacados: "Tours destacados",
    imagenNoDisponible: "Imagen no disponible",
    verDetalles: "Ver detalles",
    porPersona: "por persona",
    exploraNuestrosDestinosDisponibles: "Explora nuestros destinos disponibles",
    buscarDestinoPorNombreUbicacion: "Buscar destino por nombre o ubicación...",
    noSeEncontraronDestinos: "No se encontraron destinos.",
    // Página de reservas
    titulo: "Completa tu reserva",
    resumenTour: "Resumen del tour",
    cancelacion: "Cancelación gratuita",
    guia: "Guía incluido",
    personas: "Cantidad de personas",
    max: "Máx.",
    disponibles: "disponibles",
    metodoPago: "Método de pago",
    pagoManual: "Pago manual",
    pagoManualDesc: "Paga en nuestra oficina o al momento del tour",
    pagoTarjeta: "Pago con tarjeta",
    pagoTarjetaDesc: "Visa, Mastercard, American Express",
    efectivo: "Pago en efectivo",
    efectivoDesc: "Puedes realizar tu pago en efectivo en nuestra oficina o al momento del tour.",
    oficina: "Oficina central:",
    horario: "Horario:",
    montoCancelar: "Monto a cancelar:",
    notaPendiente: "Al confirmar tu reserva quedará en estado pendiente hasta que realices el pago en efectivo.",
    confirmarBtn: "Confirmar reserva",
    procesando: "Procesando...",
    obteniendoTC: "Obteniendo tipo de cambio...",
    errorTC: "No se pudo obtener el tipo de cambio. Intenta de nuevo.",
    resumenPago: "Resumen de pago",
    precioPersona: "Precio por persona",
    reservaConfirmada: "¡Reserva confirmada!",
    notaExito: "Tu reserva ha sido registrada. Nos pondremos en contacto contigo pronto.",
    fechaViaje: "Viaje:",
    total: "Total",
    seleccionaFechaNota: "Selecciona una fecha para continuar",
    seleccionaMetodoNota: "Selecciona un método de pago",
    por: "por",
    pagoSeguro: "Pago seguro",
    soporte: "Soporte 24/7",
    seCobraran: "Se cobrarán",
    persona: "persona",
    // Historial de facturas
    subtituloFacturas: "Consulta tus facturas, montos y fechas de registro.",
    totalFacturas: "Total de facturas",
    montoTotal: "Monto total",
    verTours: "Ver tours",
    sinFacturas: "No tienes ninguna factura registrada todavía.",
    cargandoFacturas: "Cargando historial de facturas...",
    factura: "Factura",
    viaje: "Viaje",
    cupo: "cupo",
    precioUnidad: "Precio unidad",
    registradaEl: "Registrada el",
    // Gestionar reservas (admin)
    volverPanelAdmin: "⬅ Volver al Panel Administrativo",
    gestionReservas: "Gestión de Reservas",
    confirmaVisualizaReservas: "Confirma, cancela o visualiza todas las reservas del sistema",
    todas: "Todas",
    pendientes: "Pendientes",
    confirmadas: "Confirmadas",
    totalReservas: "Total de reservas",
    noHayReservas: "No hay reservas que mostrar",
    cargandoReservas2: "Cargando reservas...",
    columnaId: "ID",
    columnaCliente: "Cliente",
    columnaTour: "Tour",
    columnaDestino: "Destino",
    columnaFecha: "Fecha",
    columnaCupos: "Cupos",
    columnaEstado: "Estado",
    columnaAcciones: "Acciones",
    btnConfirmar: "✓ Confirmar",
    btnCancelar: "✕ Cancelar",
    confirmarReservaTitle: "¿Confirmar reserva?",
    confirmarReservaText: "Esto confirmará la reserva del cliente",
    cancelarReservaTitle: "¿Cancelar reserva?",
    cancelarReservaText: "Se devolverán los cupos al tour automáticamente",
    mantener: "Mantener",
    reservaConfirmadaOk: "Reserva confirmada correctamente",
    reservaCanceladaOk: "Reserva cancelada y cupos devueltos",
    errorCargarDatos: "No se pudieron cargar los datos",
    errorConfirmar: "No se pudo confirmar la reserva",
    errorCancelar: "No se pudo cancelar la reserva",
    errorProcesar: "Error al procesar la solicitud",
    detallesReserva: "Detalles de Reserva",
    idReserva: "ID Reserva",
    infoCliente: "Información del Cliente",
    infoTour: "Información del Tour",
    detallesReservaSeccion: "Detalles de la Reserva",
    fechaTour: "Fecha del Tour",
    cuposReservados: "Cupos Reservados",
    fechaRegistro2: "Fecha de Registro",
    cerrar: "Cerrar",
    nombreLabel: "Nombre",
    correoLabel: "Correo",
    idClienteLabel: "ID Cliente",
    destinoLabel: "Destino",
    ubicacionLabel: "Ubicación",
    idTourLabel: "ID Tour",
    noDisponible: "No disponible",
    exito: "Éxito",
    error: "Error",
    // Modificar tours (admin)
    modificarTourLabel: "Modificar Tour",
    seleccionaTourModificar: "-- Selecciona el tour que deseas modificar --",
    nombreTourLabel: "Nombre del Tour",
    destinoInputLabel: "Destino",
    precioLabel: "Precio ($ USD)",
    duracionLabel: "Duración",
    breveDescLabel: "Breve Descripción",
    añadirFechasLabel: "Añadir Fechas",
    itinerarioLabel: "Itinerario",
    descripcionDetalladaLabel: "DESCRIPCIÓN DETALLADA DEL TOUR",
    imagenesLabel: "IMÁGENES DEL TOUR",
    guardarCambios: "Guardar Cambios",
    tourModificadoOk: "¡Tour modificado exitosamente!",
    errorActualizarTour: "Error al actualizar el tour.",
    noCoincidenciasDestino: "[no hay coincidencias con destinos existentes]",
    volver: "← Volver",
    cancelarSeleccion: "Cancelar selección",
    // Modificar destinos (admin)
    modificarDestinoLabel: "Modificar Destino",
    seleccionaDestinoModificar: "-- Selecciona el destino que deseas modificar --",
    nombreDestinoLabel: "Nombre del Destino",
    ubicacionLabel2: "Ubicación",
    descripcionDetalladaDestino: "Descripción Detallada",
    imagenesDestinoLabel: "Imágenes del Destino",
    volverPanel: "Volver al panel",
    destinoModificadoOk: "¡Destino modificado exitosamente!",
    errorActualizarDestino: "Error al actualizar el destino.",
    // Agregar tour
    agregarTourLabel: "Agregar tour",
    placeholderNombreTour: "Ej: Caminata Nocturna Guiada",
    placeholderDestino: "Escribe para buscar destinos registrados...",
    placeholderPrecio: "0.00",
    placeholderDuracion: "Ej: 3 horas o 2 días",
    placeholderDescBreve: "Resumen corto del tour...",
    placeholderCupos: "Cupos disponibles",
    placeholderItinerario: "Ej: 08:00 AM - Salida del hotel, 10:00 AM - Llegada al sendero...",
    descripcionDetalladaTourLabel: "DESCRIPCIÓN DETALLADA DEL TOUR",
    imagenesTourLabel: "IMAGENES DEL TOUR",
    destinoValidoRequerido: "Por favor selecciona un destino válido de la lista.",
    tourCreadoOk: "¡Excelente! El tour \"{nombre}\" ha sido creado con éxito.",
    errorGuardarTour: "Ocurrió un error al guardar el tour.",
    errorConexionServidor: "Hubo un problema de conexión con el servidor.",
    cargandoDestinos: "Cargando destinos...",
    // Agregar destino
    nombreDestinoPlaceholder: "Nombre del Destino",
    descripcionDetalladaDestinoLabel: "DESCRIPCIÓN DETALLADA",
    imagenesDestinoLabelUpper: "IMÁGENES DEL DESTINO",
    destinoCreadoOk: "¡Destino \"{nombre}\" agregado correctamente!",
    // Visualizar tours
    seleccionarTourLabel: "Seleccionar Tour",
    elegirTourDetalle: "-- Elige un tour para ver sus detalles --",
    nombreTourDetalle: "Nombre del Tour:",
    destinoVinculado: "Destino Vinculado:",
    precioDetalle: "Precio ($)",
    duracionDetalle: "Duración",
    breveDescDetalle: "Breve Descripción",
    itinerarioDetalle: "Itinerario",
    descripcionDetalladaDetalle: "Descripción Detallada",
    fechasDisponiblesCupos: "Fechas Disponibles y Cupos",
    fechaLabel: "Fecha:",
    cuposRestantes: "Cupos restantes:",
    sinFechas: "No hay fechas programadas.",
    imagenesIlustrativas: "Imágenes Ilustrativas",
    sinImagenes: "Sin imágenes cargadas.",
    eliminarTour: "Eliminar Tour",
    eliminando: "Eliminando...",
    confirmarEliminarTour: "¿Estás completamente seguro de que deseas eliminar permanentemente el tour \"{nombre}\"?",
    tourEliminadoOk: "¡Tour eliminado correctamente!",
    errorEliminarTour: "Hubo un error al intentar eliminar el tour.",
    // Visualizar destinos
    seleccionarDestinoLabel: "Seleccionar Destino",
    elegirDestinoDetalle: "-- Elige un destino para ver sus detalles --",
    nombreDestinoDetalle: "Nombre del Destino:",
    ubicacionGeografica: "Ubicación Geográfica:",
    imagenesDestinoDetalle: "Imágenes del Destino",
    eliminarDestino: "Eliminar Destino",
    confirmarEliminarDestino: "¿Estás seguro de que deseas eliminar permanentemente el destino \"{nombre}\"? Esta acción no se puede deshacer.",
    destinoEliminadoOk: "Destino eliminado correctamente.",
    errorEliminarDestino: "Hubo un problema al intentar eliminar el destino.",
    // Detalle de tours
    informacionGeneral: "Información general",
    duracion2: "Duración",
    cancelacion2: "Cancelación",
    cancelacionGratis2: "Gratuita con 24h de antelación - solicitala por correo o escribenos por WhatsApp",
    grupo2: "Grupo",
    grupoPrivado2: "",
    guia2: "Guía",
    guiaEspecializado2: "Guía especializado incluido",
    itinerario2: "Itinerario",
    desde2: "Desde",
    porPersona2: "por persona",
    fechasDisponibles2: "Fechas disponibles",
    cuposDisponibles2: "cupos disponibles",
    reservarAhora2: "Reservar ahora",
    sinCobros2: "Sin cobros hasta confirmar",
    // Panel administrativo
    volverPaginaPrincipal2: "⬅ Volver a la Página Principal",
    administrador2: "Administrador",
    panelControlAdmin: "Panel de Control Administrativo",
    subtituloPanel: "Selecciona un módulo para gestionar los recursos del sistema:",
    gestionarDestino2: "GESTIONAR DESTINO ▾",
    opciones: "Opciones",
    crearDestino2: "Crear destino",
    modificarDestino2: "Modificar destino",
    eliminarDestino2: "Eliminar destino",
    gestionarTours2: "GESTIONAR TOURS ▾",
    crearTour2: "Crear tour",
    modificarTour2: "Modificar tour",
    eliminarTour2: "Eliminar tour",
    gestionarDisponibilidad2: "GESTIONAR DISPONIBILIDAD DE TOUR",
    gestionarReservas2: "📋 GESTIONAR RESERVAS ▾",
    gestionPermisos: "Gestión de Permisos de Usuarios",
    subtituloPermisos: "Asigna o revoca privilegios de administrador a las cuentas registradas en la plataforma.",
    confirmarCambioRol: "¿Estás seguro de que deseas cambiar el rol de {correo} a \"{rol}\"?",
    rolActualizadoOk: "Rol actualizado correctamente.",
    errorCambioRol: "Ocurrió un error al procesar la solicitud.",
    sobreNosotros: "Sobre Nosotros",
    botonSobreNosotros: "Sobre Nosotros",
    mision: "Nuestra Misión",
    misionTexto: "Brindar experiencias de viaje únicas e inolvidables en Costa Rica, conectando a nuestros clientes con la riqueza natural y cultural del país, a través de tours seguros, personalizados y de alta calidad.",
    vision: "Nuestra Visión",
    visionTexto: "Ser la empresa líder en turismo de Puerto Limón - Costa Rica, reconocida por nuestra excelencia en el servicio, el compromiso con el medio ambiente y la promoción del turismo sostenible para las generaciones futuras.",
    nuestroEquipo: "Nuestro Equipo",
    nuestroEquipoTexto: "Somos un grupo apasionado de guías, planificadores y amantes de la naturaleza comprometidos con hacer de cada aventura una experiencia extraordinaria.",
  },
  en: {
    panelAdministrativo: "Administrative Panel",
    gestion: "Management:",
    irPanelAdministrativo: "Go to the administrative panel",
    perfil: "Profile",
    historialReservas: "Reservation History",
    historialPagos: "Payment History",
    cerrarSesion: "Log out",
    idioma: "Language:",
    espanol: "Spanish",
    ingles: "English",
    moneda: "Currency:",
    usd: "USD ($)",
    crc: "CRC (₡)",
    contacto: "Contact",
    contactoEmail: "Email: crtours0405@gmail.com",
    contactoTel: "Phone: +506 8716-2857",
    encuentraLugaresActividades: "Find places and activities",
    precioMinimo: "Minimum price",
    precioMaximo: "Maximum price",
    buscar: "Search",
    limpiar: "Clear",
    exploraElMundoConNosotros: "Explore the world with us",
    descubreDestinos: "Discover amazing destinations, book your trips and live unforgettable experiences.",
    verDestinos: "See destinations",
    toursDestacados: "Featured tours",
    imagenNoDisponible: "Image not available",
    verDetalles: "View details",
    porPersona: "per person",
    exploraNuestrosDestinosDisponibles: "Explore our available destinations",
    buscarDestinoPorNombreUbicacion: "Search destination by name or location...",
    noSeEncontraronDestinos: "No destinations found.",
    // Reservation page
    titulo: "Complete your reservation",
    resumenTour: "Tour summary",
    cancelacion: "Free with 24h notice - request it by email or message us on WhatsApp",
    guia: "Guide included",
    personas: "Number of people",
    max: "Max.",
    disponibles: "available",
    metodoPago: "Payment method",
    pagoManual: "Manual payment",
    pagoManualDesc: "Pay at our office or at the time of the tour",
    pagoTarjeta: "Card payment",
    pagoTarjetaDesc: "Visa, Mastercard, American Express",
    efectivo: "Cash payment",
    efectivoDesc: "You can make your payment in cash at our office or at the time of the tour.",
    oficina: "Main office:",
    horario: "Schedule:",
    montoCancelar: "Amount to pay:",
    notaPendiente: "Upon confirming, your reservation will remain pending until you make the cash payment.",
    confirmarBtn: "Confirm reservation",
    procesando: "Processing...",
    obteniendoTC: "Getting exchange rate...",
    errorTC: "Could not get the exchange rate. Please try again.",
    resumenPago: "Payment summary",
    precioPersona: "Price per person",
    reservaConfirmada: "Reservation confirmed!",
    notaExito: "Your reservation has been registered. We will contact you shortly.",
    fechaViaje: "Trip:",
    total: "Total",
    seleccionaFechaNota: "Select a date to continue",
    seleccionaMetodoNota: "Select a payment method",
    por: "for",
    pagoSeguro: "Secure payment",
    soporte: "24/7 Support",
    seCobraran: "You will be charged",
    persona: "person",
    // Payment history
    subtituloFacturas: "Check your invoices, amounts and registration dates.",
    totalFacturas: "Total invoices",
    montoTotal: "Total amount",
    verTours: "See tours",
    sinFacturas: "You don't have any invoices registered yet.",
    cargandoFacturas: "Loading payment history...",
    factura: "Invoice",
    viaje: "Trip",
    cupo: "spot",
    precioUnidad: "Unit price",
    registradaEl: "Registered on",
    // Manage reservations (admin)
    volverPanelAdmin: "⬅ Back to Admin Panel",
    gestionReservas: "Reservation Management",
    confirmaVisualizaReservas: "Confirm, cancel or view all reservations in the system",
    todas: "All",
    pendientes: "Pending",
    confirmadas: "Confirmed",
    totalReservas: "Total reservations",
    noHayReservas: "No reservations to show",
    cargandoReservas2: "Loading reservations...",
    columnaId: "ID",
    columnaCliente: "Client",
    columnaTour: "Tour",
    columnaDestino: "Destination",
    columnaFecha: "Date",
    columnaCupos: "Spots",
    columnaEstado: "Status",
    columnaAcciones: "Actions",
    btnConfirmar: "✓ Confirm",
    btnCancelar: "✕ Cancel",
    confirmarReservaTitle: "Confirm reservation?",
    confirmarReservaText: "This will confirm the client's reservation",
    cancelarReservaTitle: "Cancel reservation?",
    cancelarReservaText: "Spots will be returned to the tour automatically",
    mantener: "Keep",
    reservaConfirmadaOk: "Reservation confirmed successfully",
    reservaCanceladaOk: "Reservation cancelled and spots returned",
    errorCargarDatos: "Could not load data",
    errorConfirmar: "Could not confirm the reservation",
    errorCancelar: "Could not cancel the reservation",
    errorProcesar: "Error processing the request",
    detallesReserva: "Reservation Details",
    idReserva: "Reservation ID",
    infoCliente: "Client Information",
    infoTour: "Tour Information",
    detallesReservaSeccion: "Reservation Details",
    fechaTour: "Tour Date",
    cuposReservados: "Reserved Spots",
    fechaRegistro2: "Registration Date",
    cerrar: "Close",
    nombreLabel: "Name",
    correoLabel: "Email",
    idClienteLabel: "Client ID",
    destinoLabel: "Destination",
    ubicacionLabel: "Location",
    idTourLabel: "Tour ID",
    noDisponible: "Not available",
    exito: "Success",
    error: "Error",
    // Modify tours (admin)
    modificarTourLabel: "Modify Tour",
    seleccionaTourModificar: "-- Select the tour you want to modify --",
    nombreTourLabel: "Tour Name",
    destinoInputLabel: "Destination",
    precioLabel: "Price ($ USD)",
    duracionLabel: "Duration",
    breveDescLabel: "Short Description",
    añadirFechasLabel: "Add Dates",
    itinerarioLabel: "Itinerary",
    descripcionDetalladaLabel: "DETAILED TOUR DESCRIPTION",
    imagenesLabel: "TOUR IMAGES",
    guardarCambios: "Save Changes",
    tourModificadoOk: "Tour modified successfully!",
    errorActualizarTour: "Error updating the tour.",
    noCoincidenciasDestino: "[no matches with existing destinations]",
    volver: "← Back",
    cancelarSeleccion: "Cancel selection",
    // Modify destinations (admin)
    modificarDestinoLabel: "Modify Destination",
    seleccionaDestinoModificar: "-- Select the destination you want to modify --",
    nombreDestinoLabel: "Destination Name",
    ubicacionLabel2: "Location",
    descripcionDetalladaDestino: "Detailed Description",
    imagenesDestinoLabel: "Destination Images",
    volverPanel: "Back to panel",
    destinoModificadoOk: "Destination modified successfully!",
    errorActualizarDestino: "Error updating the destination.",
    // Add tour
    agregarTourLabel: "Add tour",
    placeholderNombreTour: "E.g: Guided Night Hike",
    placeholderDestino: "Type to search registered destinations...",
    placeholderPrecio: "0.00",
    placeholderDuracion: "E.g: 3 hours or 2 days",
    placeholderDescBreve: "Short tour summary...",
    placeholderCupos: "Available spots",
    placeholderItinerario: "E.g: 08:00 AM - Depart hotel, 10:00 AM - Arrive at trail...",
    descripcionDetalladaTourLabel: "DETAILED TOUR DESCRIPTION",
    imagenesTourLabel: "TOUR IMAGES",
    destinoValidoRequerido: "Please select a valid destination from the list.",
    tourCreadoOk: "The tour \"{nombre}\" has been created successfully!",
    errorGuardarTour: "An error occurred while saving the tour.",
    errorConexionServidor: "There was a connection problem with the server.",
    cargandoDestinos: "Loading destinations...",
    // Add destination
    nombreDestinoPlaceholder: "Destination Name",
    descripcionDetalladaDestinoLabel: "DETAILED DESCRIPTION",
    imagenesDestinoLabelUpper: "DESTINATION IMAGES",
    destinoCreadoOk: "Destination \"{nombre}\" added successfully!",
    // View tours
    seleccionarTourLabel: "Select Tour",
    elegirTourDetalle: "-- Choose a tour to view its details --",
    nombreTourDetalle: "Tour Name:",
    destinoVinculado: "Linked Destination:",
    precioDetalle: "Price ($)",
    duracionDetalle: "Duration",
    breveDescDetalle: "Short Description",
    itinerarioDetalle: "Itinerary",
    descripcionDetalladaDetalle: "Detailed Description",
    fechasDisponiblesCupos: "Available Dates and Spots",
    fechaLabel: "Date:",
    cuposRestantes: "Remaining spots:",
    sinFechas: "No scheduled dates.",
    imagenesIlustrativas: "Illustrative Images",
    sinImagenes: "No images loaded.",
    eliminarTour: "Delete Tour",
    eliminando: "Deleting...",
    confirmarEliminarTour: "Are you completely sure you want to permanently delete the tour \"{nombre}\"?",
    tourEliminadoOk: "Tour deleted successfully!",
    errorEliminarTour: "There was an error trying to delete the tour.",
    // View destinations
    seleccionarDestinoLabel: "Select Destination",
    elegirDestinoDetalle: "-- Choose a destination to view its details --",
    nombreDestinoDetalle: "Destination Name:",
    ubicacionGeografica: "Geographic Location:",
    imagenesDestinoDetalle: "Destination Images",
    eliminarDestino: "Delete Destination",
    confirmarEliminarDestino: "Are you sure you want to permanently delete the destination \"{nombre}\"? This action cannot be undone.",
    destinoEliminadoOk: "Destination deleted successfully.",
    errorEliminarDestino: "There was a problem trying to delete the destination.",
    // Tour detail
    informacionGeneral: "General information",
    duracion2: "Duration",
    cancelacion2: "Cancellation",
    cancelacionGratis2: "Free with 24h notice - request it by email or message us on WhatsApp",
    grupo2: "Group",
    grupoPrivado2: "",
    guia2: "Guide",
    guiaEspecializado2: "Specialized guide included",
    itinerario2: "Itinerary",
    desde2: "From",
    porPersona2: "per person",
    fechasDisponibles2: "Available dates",
    cuposDisponibles2: "spots available",
    reservarAhora2: "Book now",
    sinCobros2: "No charges until confirmed",
    // Admin panel
    volverPaginaPrincipal2: "⬅ Back to Home",
    administrador2: "Administrator",
    panelControlAdmin: "Administrative Control Panel",
    subtituloPanel: "Select a module to manage system resources:",
    gestionarDestino2: "MANAGE DESTINATION ▾",
    opciones: "Options",
    crearDestino2: "Create destination",
    modificarDestino2: "Modify destination",
    eliminarDestino2: "Delete destination",
    gestionarTours2: "MANAGE TOURS ▾",
    crearTour2: "Create tour",
    modificarTour2: "Modify tour",
    eliminarTour2: "Delete tour",
    gestionarDisponibilidad2: "MANAGE TOUR AVAILABILITY",
    gestionarReservas2: "📋 MANAGE RESERVATIONS ▾",
    gestionPermisos: "User Permissions Management",
    subtituloPermisos: "Assign or revoke administrator privileges to registered accounts on the platform.",
    confirmarCambioRol: "Are you sure you want to change the role of {correo} to \"{rol}\"?",
    rolActualizadoOk: "Role updated successfully.",
    errorCambioRol: "An error occurred while processing the request.",
    sobreNosotros: "About Us",
    botonSobreNosotros: "About Us",
    mision: "Our Mission",
    misionTexto: "To provide unique and unforgettable travel experiences in Costa Rica, connecting our clients with the natural and cultural richness of the country through safe, personalized, and high-quality tours.",
    vision: "Our Vision",
    visionTexto: "To be the leading tourism company in Puerto Limón - Costa Rica, recognized for our excellence in service, commitment to the environment, and promotion of sustainable tourism for future generations.",
    nuestroEquipo: "Our Team",
    nuestroEquipoTexto: "We are a passionate group of guides, planners, and nature lovers committed to making every adventure an extraordinary experience.",
  }
}

// ==========================================
// 2. TRADUCCIONES DE TOURS Y DETALLES
// ==========================================
export const traduccionesTours: Record<IdiomaClave, Record<string, string>> = {
  es: {
    informacionGeneral: "Información general",
    duracion: "Duración",
    cancelacionGratis: "Gratuita con 24h de antelación - solicitala por correo o escribenos por WhatsApp",
    grupo: "Grupo",
    grupoPrivadoDisponible: "",
    guiaEspecializadoIncluido: "Guía especializado incluido",
    itinerario: "Itinerario",
    desde: "Desde",
    fechasDisponibles: "Fechas disponibles",
    reservarAhora: "Reservar ahora",
    sinCobrosHastaConfirmar: "Sin cobros hasta confirmar",
    tourNoEncontrado: "Tour no encontrado",
    errorCargarTour: "Error al cargar el tour",
    cargar: "Cargando...",
    fecha: "Fecha",
    cupos: "cupos",
    cuposDisponibles: "cupos disponibles",
    maximo: "Máx.",
    seleccionaFecha: "Selecciona una fecha",
  },
  en: {
    informacionGeneral: "General information",
    duracion: "Duration",
    cancelacionGratis: "Free with 24h notice - request it by email or message us on WhatsApp",
    grupo: "Group",
    grupoPrivadoDisponible: "",
    guiaEspecializadoIncluido: "Specialized guide included",
    itinerario: "Itinerary",
    desde: "From",
    fechasDisponibles: "Available dates",
    reservarAhora: "Book now",
    sinCobrosHastaConfirmar: "No charges until confirmed",
    tourNoEncontrado: "Tour not found",
    errorCargarTour: "Error loading the tour",
    cargar: "Loading...",
    fecha: "Date",
    cupos: "spots",
    cuposDisponibles: "spots available",
    maximo: "Max.",
    seleccionaFecha: "Select a date",
  }
}

// ==========================================
// 3. TRADUCCIONES DE AUTENTICACIÓN (AUTH)
// ==========================================
export const traduccionesAuth: Record<IdiomaClave, Record<string, string>> = {
  es: {
    bienvenidoABordo: "¡Bienvenido a bordo!",
    correoElectronico: "Correo electrónico",
    contrasena: "Contraseña",
    olvidasteTuContrasena: "¿Olvidaste tu contraseña?",
    iniciarSesion: "Iniciar sesión",
    noTienesCuenta: "¿No tienes una cuenta?",
    registrateAqui: "Regístrate aquí",
    creaTuCuenta: "Crea tu cuenta",
    uneteACRTours: "¡Únete a CR Tours y comienza tu aventura!",
    nombre: "Nombre",
    apellido: "Apellido",
    crearCuenta: "Crear cuenta",
    yaTienesCuenta: "¿Ya tienes una cuenta?",
    iniciaSesionAqui: "Inicia sesión aquí",
    recuperarContrasena: "Recuperar contraseña",
    ingresaTuCorreoCodigo: "Ingresa tu correo y te enviaremos un código.",
    codigo6Digitos: "Código de 6 dígitos",
    nuevaContrasena: "Nueva contraseña",
    cambiarContrasena: "Cambiar contraseña",
    reenviarCodigo: "Reenviar código",
    contrasenaCambiadaExito: "¡Contraseña cambiada con éxito!",
    irAIniciarSesion: "Ir a iniciar sesión",
    enviaCodigo: "Enviar código",
    enviando: "Enviando...",
    ingresaTuCorreo: "Ingresa tu correo",
    correoNoValido: "Por favor ingresa un correo electrónico válido",
    correoValidoRequerido: "Por favor ingresar un correo válido",
    contrasenaRequerida: "Por favor ingresar una contraseña",
    contrasenaMinima: "La contraseña debe tener al menos 6 caracteres",
    completaCampos: "Completa todos los campos",
    errorConexion: "Error de conexión",
    errorIniciarSesion: "Error al iniciar sesión",
    errorCrearCuenta: "Error al crear la cuenta",
    errorEnviarCodigo: "Error al enviar el código",
    codigoIncorrecto: "Código incorrecto"
  },
  en: {
    bienvenidoABordo: "Welcome aboard!",
    correoElectronico: "Email",
    contrasena: "Password",
    olvidasteTuContrasena: "Forgot your password?",
    iniciarSesion: "Sign in",
    noTienesCuenta: "Don't have an account?",
    registrateAqui: "Sign up here",
    creaTuCuenta: "Create your account",
    uneteACRTours: "Join CR Tours and start your adventure!",
    nombre: "First name",
    apellido: "Last name",
    crearCuenta: "Create account",
    yaTienesCuenta: "Already have an account?",
    iniciaSesionAqui: "Sign in here",
    recuperarContrasena: "Reset password",
    ingresaTuCorreoCodigo: "Enter your email and we will send you a code.",
    codigo6Digitos: "6-digit code",
    nuevaContrasena: "New password",
    cambiarContrasena: "Change password",
    reenviarCodigo: "Resend code",
    contrasenaCambiadaExito: "Password changed successfully!",
    irAIniciarSesion: "Go to sign in",
    enviaCodigo: "Send code",
    enviando: "Sending...",
    ingresaTuCorreo: "Enter your email",
    correoNoValido: "Please enter a valid email address",
    correoValidoRequerido: "Please enter a valid email",
    contrasenaRequerida: "Please enter a password",
    contrasenaMinima: "Password must be at least 6 characters",
    completaCampos: "Complete all fields",
    errorConexion: "Connection error",
    errorIniciarSesion: "Error signing in",
    errorCrearCuenta: "Error creating account",
    errorEnviarCodigo: "Error sending the code",
    codigoIncorrecto: "Incorrect code"
  }
}

// ==========================================
// 4. TRADUCCIONES DEL HISTORIAL DE RESERVAS
// ==========================================
export const traduccionesHistorial: Record<IdiomaClave, Record<string, string>> = {
  es: {
    misReservas: "Mis reservas",
    cargandoReservas: "Cargando reservas...",
    noTienesReservas: "No tienes reservas registradas aún.",
    explorarTours: "Explorar tours",
    reservadoEl: "el",
    estadoConfirmada: "Confirmada",
    estadoPendiente: "Pendiente",
    estadoCancelada: "Cancelada"
  },
  en: {
    misReservas: "My reservations",
    cargandoReservas: "Loading reservations...",
    noTienesReservas: "You don't have any reservations yet.",
    explorarTours: "Explore tours",
    reservadoEl: "on",
    estadoConfirmada: "Confirmed",
    estadoPendiente: "Pending",
    estadoCancelada: "Cancelled"
  }
}

// ==========================================
// 5. TRADUCCIONES DEL PANEL ADMINISTRATIVO
// ==========================================
export const traduccionesAdmin: Record<IdiomaClave, Record<string, string>> = {
  es: {
    volverPaginaPrincipal: "⬅ Volver a la Página Principal",
    panelControlAdministrativo: "Panel de Control Administrativo",
    seleccionaModulo: "Selecciona un módulo para gestionar los recursos del sistema:",
    gestionarDestino: "Gestionar destino",
    crearDestino: "Crear destino",
    modificarDestino: "Modificar destino",
    eliminarDestino: "Eliminar destino",
    gestionarTours: "Gestionar tours",
    crearTour: "Crear tour",
    modificarTour: "Modificar tour",
    eliminarTour: "Eliminar tour",
    gestionarDisponibilidadTour: "Gestionar disponibilidad de tour",
    gestionarReservas: "Gestionar reservas",
    gestionPermisosUsuarios: "Gestión de Permisos de Usuarios",
    asignaRevocaPrivilegios: "Asigna o revoca privilegios de administrador a las cuentas registradas en la plataforma.",
    usuario: "Usuario",
    correo: "Correo",
    rolActual: "Rol Actual",
    accion: "Acción",
    quitarAdmin: "❌ Quitar Admin",
    hacerAdmin: "🔑 Hacer Admin",
    administrador: "Administrador",
    cliente: "Cliente",
    nombreDelDestino: "Nombre del Destino",
    ubicacion: "Ubicación",
    breveDescripcion: "Breve Descripción",
    descripcionDetallada: "DESCRIPCIÓN DETALLADA",
    imagenesDelDestino: "IMÁGENES DEL DESTINO",
    seleccionarArchivos: "Seleccionar Archivos",
    cancelar: "Cancelar",
    agregarDestino: "Agregar destino",
    guardando: "Guardando...",
    destinoAgregadoExito: "¡Destino agregado correctamente!",
    errorGuardarDestino: "Error al guardar el destino"
  },
  en: {
    volverPaginaPrincipal: "⬅ Back to Home",
    panelControlAdministrativo: "Administrative Control Panel",
    seleccionaModulo: "Select a module to manage system resources:",
    gestionarDestino: "Manage destination",
    crearDestino: "Create destination",
    modificarDestino: "Modify destination",
    eliminarDestino: "Delete destination",
    gestionarTours: "Manage tours",
    crearTour: "Create tour",
    modificarTour: "Modify tour",
    eliminarTour: "Delete tour",
    gestionarDisponibilidadTour: "Manage tour availability",
    gestionarReservas: "Manage reservations",
    gestionPermisosUsuarios: "User permissions management",
    asignaRevocaPrivilegios: "Assign or revoke administrator privileges to registered accounts on the platform.",
    usuario: "User",
    correo: "Email",
    rolActual: "Current role",
    accion: "Action",
    quitarAdmin: "❌ Remove Admin",
    hacerAdmin: "🔑 Make Admin",
    administrador: "Administrator",
    cliente: "Client",
    nombreDelDestino: "Destination name",
    ubicacion: "Location",
    breveDescripcion: "Short description",
    descripcionDetallada: "DETAILED DESCRIPTION",
    imagenesDelDestino: "DESTINATION IMAGES",
    seleccionarArchivos: "Select files",
    cancelar: "Cancel",
    agregarDestino: "Add destination",
    guardando: "Saving...",
    destinoAgregadoExito: "Destination added successfully!",
    errorGuardarDestino: "Error saving the destination"
  }
}

// ==========================================
// 6. TRADUCCIONES DE STRIPE / PRUEBAS
// ==========================================
export const traduccionesStripe: Record<IdiomaClave, Record<string, string>> = {
  es: {
    testIntegracionStripe: "Test de Integración Stripe",
    configuracionPago: "Configuración del Pago",
    montoUSD: "Monto (USD)",
    descripcionPago: "Descripción",
    formularioPago: "Formulario de Pago",
    pagoExitoso: "¡Pago Exitoso!",
    idPaymentIntent: "ID del Payment Intent:",
    montoPagado: "Monto pagado:",
    realizarOtroPago: "Realizar otro pago",
    informacionPrueba: "Información de Prueba",
    paginaTemporalStripe: "Esta es una página temporal para probar la integración con Stripe",
    tarjetaPrueba: "Usa tarjetas de prueba de Stripe (ej: 4242 4242 4242 4242)",
    variablesEntorno: "Asegúrate de tener las variables de entorno configuradas",
    pagosModoPrueba: "Los pagos se procesan en modo de prueba"
  },
  en: {
    testIntegracionStripe: "Stripe Integration Test",
    configuracionPago: "Payment setup",
    montoUSD: "Amount (USD)",
    descripcionPago: "Description",
    formularioPago: "Payment form",
    pagoExitoso: "Payment successful!",
    idPaymentIntent: "Payment Intent ID:",
    montoPagado: "Amount paid:",
    realizarOtroPago: "Make another payment",
    informacionPrueba: "Test information",
    paginaTemporalStripe: "This is a temporary page to test Stripe integration",
    tarjetaPrueba: "Use Stripe test cards (eg: 4242 4242 4242 4242)",
    variablesEntorno: "Make sure your environment variables are configured",
    pagosModoPrueba: "Payments are processed in test mode"
  }
}

// ==========================================
// FUNCIÓN CENTRAL INTEGRADORA i18
// ==========================================
export function i18(clave: string, idioma: IdiomaClave = "es"): string {
  return (
    traduccionesUI[idioma]?.[clave] ??
    traduccionesTours[idioma]?.[clave] ??
    traduccionesAuth[idioma]?.[clave] ??
    traduccionesHistorial[idioma]?.[clave] ??
    traduccionesAdmin[idioma]?.[clave] ??
    traduccionesStripe[idioma]?.[clave] ??
    clave
  )
}