export type IdiomaClave = "es" | "en"

export const idiomasDisponibles: IdiomaClave[] = ["es", "en"]

// ==========================================
// 1. TRADUCCIONES DE LA INTERFAZ GENERAL (UI)
// ==========================================
export const traduccionesUI: Record<IdiomaClave, Record<string, string>> = {
  es: {
    panelAdministrativo: "Panel Administrativo",
    gestion: "Gestión:",
    irPanelAdministrativo: "Ir al panel administrativo",
    perfil: "Perfil",
    historialReservas: "Historial Reservas",
    historialPagos: "Historial Pagos",
    cerrarSesion: "Cerrar sesión",
    idioma: "Idioma:",
    espanol: "Español",
    ingles: "Inglés",
    moneda: "Moneda:",
    usd: "USD ($)",
    crc: "CRC (₡)",
    contacto: "Contacto",
    contactoEmail: "Email: contacto@tours.com",
    contactoTel: "Tel: +506 8888-8888",
    encuentraLugaresActividades: "Encuentra lugares y actividades",
    precioMinimo: "Precio mínimo",
    precioMaximo: "Precio máximo",
    buscar: "Buscar",
    limpiar: "Limpiar",
    exploraElMundoConNosotros: "Explora el mundo con nosotros",
    descubreDestinos: "Descubre destinos increíbles, reserva tus viajes y vive experiencias inolvidables.",
    verDestinos: "Ver destinos",
    toursDestacados: "Tours destacados",
    imagenNoDisponible: "Imagen no disponible",
    verDetalles: "Ver detalles",
    porPersona: "por persona",
    exploraNuestrosDestinosDisponibles: "Explora nuestros destinos disponibles",
    buscarDestinoPorNombreUbicacion: "Buscar destino por nombre o ubicación...",
    noSeEncontraronDestinos: "No se encontraron destinos.",
    // Página de reservas
    titulo: "Completa tu reserva",
    resumenTour: "Resumen del tour",
    cancelacion: "Cancelación gratuita",
    guia: "Guía incluido",
    personas: "Cantidad de personas",
    max: "Máx.",
    disponibles: "disponibles",
    metodoPago: "Método de pago",
    pagoManual: "Pago manual",
    pagoManualDesc: "Paga en nuestra oficina o al momento del tour",
    pagoTarjeta: "Pago con tarjeta",
    pagoTarjetaDesc: "Visa, Mastercard, American Express",
    efectivo: "Pago en efectivo",
    efectivoDesc: "Puedes realizar tu pago en efectivo en nuestra oficina o al momento del tour.",
    oficina: "Oficina central:",
    horario: "Horario:",
    montoCancelar: "Monto a cancelar:",
    notaPendiente: "Al confirmar tu reserva quedará en estado pendiente hasta que realices el pago en efectivo.",
    confirmarBtn: "Confirmar reserva",
    procesando: "Procesando...",
    obteniendoTC: "Obteniendo tipo de cambio...",
    errorTC: "No se pudo obtener el tipo de cambio. Intenta de nuevo.",
    resumenPago: "Resumen de pago",
    precioPersona: "Precio por persona",
    reservaConfirmada: "¡Reserva confirmada!",
    notaExito: "Tu reserva ha sido registrada. Nos pondremos en contacto contigo pronto.",
    fechaViaje: "Viaje:",
    total: "Total",
    seleccionaFechaNota: "Selecciona una fecha para continuar",
    seleccionaMetodoNota: "Selecciona un método de pago",
    por: "por",
    pagoSeguro: "Pago seguro",
    soporte: "Soporte 24/7",
    seCobraran: "Se cobrarán",
    persona: "persona",
    // Historial de facturas
    historialPagosTitulo: "Historial de pagos",
    subtituloFacturas: "Consulta tus facturas, montos y fechas de registro.",
    totalFacturas: "Total de facturas",
    montoTotal: "Monto total",
    verTours: "Ver tours",
    sinFacturas: "No tienes ninguna factura registrada todavía.",
    cargandoFacturas: "Cargando historial de facturas...",
    factura: "Factura",
    viaje: "Viaje",
    cupo: "cupo",
    precioUnidad: "Precio unidad",
    registradaEl: "Registrada el",
  },
  en: {
    panelAdministrativo: "Administrative Panel",
    gestion: "Management:",
    irPanelAdministrativo: "Go to the administrative panel",
    perfil: "Profile",
    historialReservas: "Reservation History",
    historialPagos: "Payment History",
    cerrarSesion: "Log out",
    idioma: "Language:",
    espanol: "Spanish",
    ingles: "English",
    moneda: "Currency:",
    usd: "USD ($)",
    crc: "CRC (₡)",
    contacto: "Contact",
    contactoEmail: "Email: contacto@tours.com",
    contactoTel: "Phone: +506 8888-8888",
    encuentraLugaresActividades: "Find places and activities",
    precioMinimo: "Minimum price",
    precioMaximo: "Maximum price",
    buscar: "Search",
    limpiar: "Clear",
    exploraElMundoConNosotros: "Explore the world with us",
    descubreDestinos: "Discover amazing destinations, book your trips and live unforgettable experiences.",
    verDestinos: "See destinations",
    toursDestacados: "Featured tours",
    imagenNoDisponible: "Image not available",
    verDetalles: "View details",
    porPersona: "per person",
    exploraNuestrosDestinosDisponibles: "Explore our available destinations",
    buscarDestinoPorNombreUbicacion: "Search destination by name or location...",
    noSeEncontraronDestinos: "No destinations found.",
    // Reservation page
    titulo: "Complete your reservation",
    resumenTour: "Tour summary",
    cancelacion: "Free cancellation",
    guia: "Guide included",
    personas: "Number of people",
    max: "Max.",
    disponibles: "available",
    metodoPago: "Payment method",
    pagoManual: "Manual payment",
    pagoManualDesc: "Pay at our office or at the time of the tour",
    pagoTarjeta: "Card payment",
    pagoTarjetaDesc: "Visa, Mastercard, American Express",
    efectivo: "Cash payment",
    efectivoDesc: "You can make your payment in cash at our office or at the time of the tour.",
    oficina: "Main office:",
    horario: "Schedule:",
    montoCancelar: "Amount to pay:",
    notaPendiente: "Upon confirming, your reservation will remain pending until you make the cash payment.",
    confirmarBtn: "Confirm reservation",
    procesando: "Processing...",
    obteniendoTC: "Getting exchange rate...",
    errorTC: "Could not get the exchange rate. Please try again.",
    resumenPago: "Payment summary",
    precioPersona: "Price per person",
    reservaConfirmada: "Reservation confirmed!",
    notaExito: "Your reservation has been registered. We will contact you shortly.",
    fechaViaje: "Trip:",
    total: "Total",
    seleccionaFechaNota: "Select a date to continue",
    seleccionaMetodoNota: "Select a payment method",
    por: "for",
    pagoSeguro: "Secure payment",
    soporte: "24/7 Support",
    seCobraran: "You will be charged",
    persona: "person",
    // Payment history
    historialPagosTitulo: "Payment history",
    subtituloFacturas: "Check your invoices, amounts and registration dates.",
    totalFacturas: "Total invoices",
    montoTotal: "Total amount",
    verTours: "See tours",
    sinFacturas: "You don't have any invoices registered yet.",
    cargandoFacturas: "Loading payment history...",
    factura: "Invoice",
    viaje: "Trip",
    cupo: "spot",
    precioUnidad: "Unit price",
    registradaEl: "Registered on",
  }
}

// ==========================================
// 2. TRADUCCIONES DE TOURS Y DETALLES
// ==========================================
export const traduccionesTours: Record<IdiomaClave, Record<string, string>> = {
  es: {
    informacionGeneral: "Información general",
    duracion: "Duración",
    cancelacionGratis: "Gratuita con 24h de antelación",
    grupo: "Grupo",
    grupoPrivadoDisponible: "Grupo privado disponible",
    guiaEspecializadoIncluido: "Guía especializado incluido",
    itinerario: "Itinerario",
    desde: "Desde",
    fechasDisponibles: "Fechas disponibles",
    reservarAhora: "Reservar ahora",
    sinCobrosHastaConfirmar: "Sin cobros hasta confirmar",
    tourNoEncontrado: "Tour no encontrado",
    errorCargarTour: "Error al cargar el tour",
    cargar: "Cargando...",
    fecha: "Fecha",
    cupos: "cupos",
    cuposDisponibles: "cupos disponibles",
    maximo: "Máx.",
    seleccionaFecha: "Selecciona una fecha",
  },
  en: {
    informacionGeneral: "General information",
    duracion: "Duration",
    cancelacionGratis: "Free with 24h notice",
    grupo: "Group",
    grupoPrivadoDisponible: "Private group available",
    guiaEspecializadoIncluido: "Specialized guide included",
    itinerario: "Itinerary",
    desde: "From",
    fechasDisponibles: "Available dates",
    reservarAhora: "Book now",
    sinCobrosHastaConfirmar: "No charges until confirmed",
    tourNoEncontrado: "Tour not found",
    errorCargarTour: "Error loading the tour",
    cargar: "Loading...",
    fecha: "Date",
    cupos: "spots",
    cuposDisponibles: "spots available",
    maximo: "Max.",
    seleccionaFecha: "Select a date",
  }
}

// ==========================================
// 3. TRADUCCIONES DE AUTENTICACIÓN (AUTH)
// ==========================================
export const traduccionesAuth: Record<IdiomaClave, Record<string, string>> = {
  es: {
    bienvenidoABordo: "¡Bienvenido a bordo!",
    correoElectronico: "Correo electrónico",
    contrasena: "Contraseña",
    olvidasteTuContrasena: "¿Olvidaste tu contraseña?",
    iniciarSesion: "Iniciar sesión",
    noTienesCuenta: "¿No tienes una cuenta?",
    registrateAqui: "Regístrate aquí",
    creaTuCuenta: "Crea tu cuenta",
    uneteACRTours: "¡Únete a CR Tours y comienza tu aventura!",
    nombre: "Nombre",
    apellido: "Apellido",
    crearCuenta: "Crear cuenta",
    yaTienesCuenta: "¿Ya tienes una cuenta?",
    iniciaSesionAqui: "Inicia sesión aquí",
    recuperarContrasena: "Recuperar contraseña",
    ingresaTuCorreoCodigo: "Ingresa tu correo y te enviaremos un código.",
    codigo6Digitos: "Código de 6 dígitos",
    nuevaContrasena: "Nueva contraseña",
    cambiarContrasena: "Cambiar contraseña",
    reenviarCodigo: "Reenviar código",
    contrasenaCambiadaExito: "¡Contraseña cambiada con éxito!",
    irAIniciarSesion: "Ir a iniciar sesión",
    enviaCodigo: "Enviar código",
    enviando: "Enviando...",
    ingresaTuCorreo: "Ingresa tu correo",
    correoNoValido: "Por favor ingresa un correo electrónico válido",
    correoValidoRequerido: "Por favor ingresar un correo válido",
    contrasenaRequerida: "Por favor ingresar una contraseña",
    contrasenaMinima: "La contraseña debe tener al menos 6 caracteres",
    completaCampos: "Completa todos los campos",
    errorConexion: "Error de conexión",
    errorIniciarSesion: "Error al iniciar sesión",
    errorCrearCuenta: "Error al crear la cuenta",
    errorEnviarCodigo: "Error al enviar el código",
    codigoIncorrecto: "Código incorrecto"
  },
  en: {
    bienvenidoABordo: "Welcome aboard!",
    correoElectronico: "Email",
    contrasena: "Password",
    olvidasteTuContrasena: "Forgot your password?",
    iniciarSesion: "Sign in",
    noTienesCuenta: "Don't have an account?",
    registrateAqui: "Sign up here",
    creaTuCuenta: "Create your account",
    uneteACRTours: "Join CR Tours and start your adventure!",
    nombre: "First name",
    apellido: "Last name",
    crearCuenta: "Create account",
    yaTienesCuenta: "Already have an account?",
    iniciaSesionAqui: "Sign in here",
    recuperarContrasena: "Reset password",
    ingresaTuCorreoCodigo: "Enter your email and we will send you a code.",
    codigo6Digitos: "6-digit code",
    nuevaContrasena: "New password",
    cambiarContrasena: "Change password",
    reenviarCodigo: "Resend code",
    contrasenaCambiadaExito: "Password changed successfully!",
    irAIniciarSesion: "Go to sign in",
    enviaCodigo: "Send code",
    enviando: "Sending...",
    ingresaTuCorreo: "Enter your email",
    correoNoValido: "Please enter a valid email address",
    correoValidoRequerido: "Please enter a valid email",
    contrasenaRequerida: "Please enter a password",
    contrasenaMinima: "Password must be at least 6 characters",
    completaCampos: "Complete all fields",
    errorConexion: "Connection error",
    errorIniciarSesion: "Error signing in",
    errorCrearCuenta: "Error creating account",
    errorEnviarCodigo: "Error sending the code",
    codigoIncorrecto: "Incorrect code"
  }
}

// ==========================================
// 4. TRADUCCIONES DEL HISTORIAL DE RESERVAS
// ==========================================
export const traduccionesHistorial: Record<IdiomaClave, Record<string, string>> = {
  es: {
    misReservas: "Mis reservas",
    cargandoReservas: "Cargando reservas...",
    noTienesReservas: "No tienes reservas registradas aún.",
    explorarTours: "Explorar tours",
    reservadoEl: "el",
    estadoConfirmada: "Confirmada",
    estadoPendiente: "Pendiente",
    estadoCancelada: "Cancelada"
  },
  en: {
    misReservas: "My reservations",
    cargandoReservas: "Loading reservations...",
    noTienesReservas: "You don't have any reservations yet.",
    explorarTours: "Explore tours",
    reservadoEl: "on",
    estadoConfirmada: "Confirmed",
    estadoPendiente: "Pending",
    estadoCancelada: "Cancelled"
  }
}

// ==========================================
// 5. TRADUCCIONES DEL PANEL ADMINISTRATIVO
// ==========================================
export const traduccionesAdmin: Record<IdiomaClave, Record<string, string>> = {
  es: {
    volverPaginaPrincipal: "⬅ Volver a la Página Principal",
    panelControlAdministrativo: "Panel de Control Administrativo",
    seleccionaModulo: "Selecciona un módulo para gestionar los recursos del sistema:",
    gestionarDestino: "Gestionar destino",
    crearDestino: "Crear destino",
    modificarDestino: "Modificar destino",
    eliminarDestino: "Eliminar destino",
    gestionarTours: "Gestionar tours",
    crearTour: "Crear tour",
    modificarTour: "Modificar tour",
    eliminarTour: "Eliminar tour",
    gestionarDisponibilidadTour: "Gestionar disponibilidad de tour",
    gestionarReservas: "Gestionar reservas",
    gestionPermisosUsuarios: "Gestión de Permisos de Usuarios",
    asignaRevocaPrivilegios: "Asigna o revoca privilegios de administrador a las cuentas registradas en la plataforma.",
    usuario: "Usuario",
    correo: "Correo",
    rolActual: "Rol Actual",
    accion: "Acción",
    quitarAdmin: "❌ Quitar Admin",
    hacerAdmin: "🔑 Hacer Admin",
    administrador: "Administrador",
    cliente: "Cliente",
    nombreDelDestino: "Nombre del Destino",
    ubicacion: "Ubicación",
    breveDescripcion: "Breve Descripción",
    descripcionDetallada: "DESCRIPCIÓN DETALLADA",
    imagenesDelDestino: "IMÁGENES DEL DESTINO",
    seleccionarArchivos: "Seleccionar Archivos",
    cancelar: "Cancelar",
    agregarDestino: "Agregar destino",
    guardando: "Guardando...",
    destinoAgregadoExito: "¡Destino agregado correctamente!",
    errorGuardarDestino: "Error al guardar el destino"
  },
  en: {
    volverPaginaPrincipal: "⬅ Back to Home",
    panelControlAdministrativo: "Administrative Control Panel",
    seleccionaModulo: "Select a module to manage system resources:",
    gestionarDestino: "Manage destination",
    crearDestino: "Create destination",
    modificarDestino: "Modify destination",
    eliminarDestino: "Delete destination",
    gestionarTours: "Manage tours",
    crearTour: "Create tour",
    modificarTour: "Modify tour",
    eliminarTour: "Delete tour",
    gestionarDisponibilidadTour: "Manage tour availability",
    gestionarReservas: "Manage reservations",
    gestionPermisosUsuarios: "User permissions management",
    asignaRevocaPrivilegios: "Assign or revoke administrator privileges to registered accounts on the platform.",
    usuario: "User",
    correo: "Email",
    rolActual: "Current role",
    accion: "Action",
    quitarAdmin: "❌ Remove Admin",
    hacerAdmin: "🔑 Make Admin",
    administrador: "Administrator",
    cliente: "Client",
    nombreDelDestino: "Destination name",
    ubicacion: "Location",
    breveDescripcion: "Short description",
    descripcionDetallada: "DETAILED DESCRIPTION",
    imagenesDelDestino: "DESTINATION IMAGES",
    seleccionarArchivos: "Select files",
    cancelar: "Cancel",
    agregarDestino: "Add destination",
    guardando: "Saving...",
    destinoAgregadoExito: "Destination added successfully!",
    errorGuardarDestino: "Error saving the destination"
  }
}

// ==========================================
// 6. TRADUCCIONES DE STRIPE / PRUEBAS
// ==========================================
export const traduccionesStripe: Record<IdiomaClave, Record<string, string>> = {
  es: {
    testIntegracionStripe: "Test de Integración Stripe",
    configuracionPago: "Configuración del Pago",
    montoUSD: "Monto (USD)",
    descripcionPago: "Descripción",
    formularioPago: "Formulario de Pago",
    pagoExitoso: "¡Pago Exitoso!",
    idPaymentIntent: "ID del Payment Intent:",
    montoPagado: "Monto pagado:",
    realizarOtroPago: "Realizar otro pago",
    informacionPrueba: "Información de Prueba",
    paginaTemporalStripe: "Esta es una página temporal para probar la integración con Stripe",
    tarjetaPrueba: "Usa tarjetas de prueba de Stripe (ej: 4242 4242 4242 4242)",
    variablesEntorno: "Asegúrate de tener las variables de entorno configuradas",
    pagosModoPrueba: "Los pagos se procesan en modo de prueba"
  },
  en: {
    testIntegracionStripe: "Stripe Integration Test",
    configuracionPago: "Payment setup",
    montoUSD: "Amount (USD)",
    descripcionPago: "Description",
    formularioPago: "Payment form",
    pagoExitoso: "Payment successful!",
    idPaymentIntent: "Payment Intent ID:",
    montoPagado: "Amount paid:",
    realizarOtroPago: "Make another payment",
    informacionPrueba: "Test information",
    paginaTemporalStripe: "This is a temporary page to test Stripe integration",
    tarjetaPrueba: "Use Stripe test cards (eg: 4242 4242 4242 4242)",
    variablesEntorno: "Make sure your environment variables are configured",
    pagosModoPrueba: "Payments are processed in test mode"
  }
}

// ==========================================
// FUNCIÓN CENTRAL INTEGRADORA i18
// ==========================================
export function i18(clave: string, idioma: IdiomaClave = "es"): string {
  return (
    traduccionesUI[idioma]?.[clave] ??
    traduccionesTours[idioma]?.[clave] ??
    traduccionesAuth[idioma]?.[clave] ??
    traduccionesHistorial[idioma]?.[clave] ??
    traduccionesAdmin[idioma]?.[clave] ??
    traduccionesStripe[idioma]?.[clave] ??
    clave
  )
}